// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygmcaurzakyzgovpvpbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnbWNhdXJ6YWt5emdvdnB2cGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjI2NjIsImV4cCI6MjA2NjU5ODY2Mn0.TVBC2jnj9zK9YvkFrcI-SVi4KkYwp_7b7vPWenOIS8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);